# Generated by Django 5.0 on 2024-08-03 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appeal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appeal',
            name='service',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Выбранная услуга'),
        ),
    ]
