# Generated by Django 5.0 on 2024-07-29 11:24

import core.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Название раздела')),
                ('left_content', models.TextField(verbose_name='Контент слева')),
                ('right_content', models.TextField(verbose_name='Контент справа')),
            ],
            options={
                'verbose_name': 'Раздел обо мне',
                'verbose_name_plural': 'Раздел обо мне',
            },
        ),
        migrations.CreateModel(
            name='Meta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='Мета title')),
                ('description', models.CharField(max_length=256, verbose_name='Мета description')),
                ('intro_text', models.CharField(max_length=256, verbose_name='Печатающийся текст')),
            ],
            options={
                'verbose_name': 'Мета информация',
                'verbose_name_plural': 'Мета информация',
            },
        ),
        migrations.CreateModel(
            name='AboutImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=core.models.image_path, verbose_name='Изображение')),
                ('name', models.CharField(blank=True, max_length=128, null=True, verbose_name='Название')),
                ('about', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.about', verbose_name='Раздел')),
            ],
            options={
                'verbose_name': 'Изображения раздела обо мне',
                'verbose_name_plural': 'Изображения раздела обо мне',
            },
        ),
    ]
