# Generated by Django 5.0 on 2024-07-29 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SectionName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=64, verbose_name='Название раздела продуктов')),
                ('review_name', models.CharField(max_length=64, verbose_name='Название раздела отзывов')),
            ],
            options={
                'verbose_name': 'Название раздела',
                'verbose_name_plural': 'Названия разделов',
            },
        ),
    ]
