# Generated by Django 5.0 on 2024-07-29 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0002_review_content_review_date_review_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-created_at', 'published'], 'verbose_name': 'Отзыв', 'verbose_name_plural': 'Отзывы'},
        ),
    ]
